# Build and publish the project mdBook.
#
# SPDX-License-Identifier: MIT

name: Publish documentation

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - docs/**
      - .github/workflows/publish-docs.yml
  push:
    branches: [main]
    paths:
      - docs/**
      - .github/workflows/publish-docs.yml

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: "0.4.52"

      - name: Build documentation
        run: mdbook build docs

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          name: github-pages
          path: docs/book

  publish:
    name: Publish documentation
    if: github.event_name != 'pull_request' && github.repository_owner == 'OpenDevicePartnership'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy GitHub Pages site
        id: deployment
        uses: actions/deploy-pages@v5
        with:
          artifact_name: github-pages
